// Code generated by fastparse. DO NOT EDIT.
//go:build arm64

#include "textflag.h"

// func needsEscapingASM(s string, quote byte, mode int) bool
TEXT ·needsEscapingASM(SB), NOSPLIT, $0-34
	// For now, use generic implementation
	// TODO: Implement SIMD-optimized version using NEON
	
	// Get string pointer and length
	MOVD s_base+0(FP), R0    // R0 = string data pointer
	MOVD s_len+8(FP), R1     // R1 = string length
	MOVBU quote+16(FP), R2   // R2 = quote character
	MOVD mode+24(FP), R3     // R3 = mode
	
	// Fast path: empty string needs no escaping
	CBZ R1, no_escape
	
	// Simple scalar loop for now
	// TODO: Vectorize with NEON
loop:
	MOVBU (R0), R4           // R4 = current byte
	
	// Check if byte == quote
	CMP R2, R4
	BEQ needs_escape
	
	// Check if byte == backslash
	MOVD $'\\', R5
	CMP R5, R4
	BEQ needs_escape
	
	// Check if byte < ' '
	MOVD $' ', R5
	CMP R5, R4
	BLT needs_escape
	
	// Check if byte == 0x7F
	MOVD $0x7F, R5
	CMP R5, R4
	BEQ needs_escape
	
	// Check for non-ASCII in ASCII mode
	MOVD $1, R5              // ModeASCII
	CMP R5, R3
	BNE check_next
	MOVD $0x80, R5
	CMP R5, R4
	BGE needs_escape
	
check_next:
	ADD $1, R0
	SUB $1, R1
	CBNZ R1, loop
	
no_escape:
	MOVD $0, R0
	MOVB R0, ret+32(FP)
	RET
	
needs_escape:
	MOVD $1, R0
	MOVB R0, ret+32(FP)
	RET

